### ISSUE TITLE
The precommit hook is failing when you commit: "Error: RxJS could not find any global context (window, self, global)"

### ISSUE THREAD

**Issue by mstange** [firefox-devtools/Gecko-Profiler-Addon#66]
```
$ git commit -m "Change description again."

> husky - npm run -s precommit

/Users/mstange/code/Gecko-Profiler-Addon/node_modules/rxjs/util/root.js:15
    throw new Error('RxJS could not find any global context (window, self, global)');
    ^

Error: RxJS could not find any global context (window, self, global)
    at /Users/mstange/code/Gecko-Profiler-Addon/node_modules/rxjs/util/root.js:15:11
    at Object.<anonymous> (/Users/mstange/code/Gecko-Profiler-Addon/node_modules/rxjs/util/root.js:16:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mstange/code/Gecko-Profiler-Addon/node_modules/rxjs/Observable.js:2:14)

> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'
```

**Comment by clarkbw** [comment]
Looks like this is caused by this change: https://github.com/ReactiveX/rxjs/issues/2598

**Comment by jayphelps** [comment]
5.3.3 has been published and resolves the issue.

**Comment by clarkbw** [comment]
`rm node_modules && npm install` seems to fix the issue.  Thanks @jayphelps
